// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HoangTrungThong774.Data;

namespace HoangTrungThong774.Migrations
{
    [DbContext(typeof(ApplictionContext))]
    [Migration("20211006004537_Create_Table_HTTHTT0774")]
    partial class Create_Table_HTTHTT0774
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("HoangTrungThong774.Models.HTT0774", b =>
                {
                    b.Property<string>("HTTId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HTTGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HTTName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HTTId");

                    b.ToTable("HTT0774");
                });

            modelBuilder.Entity("HoangTrungThong774.Models.PersonHTT774", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("PersonHTT774");
                });
#pragma warning restore 612, 618
        }
    }
}
